version: "3.4"

services:
  api:
    build: .
    container_name: sberCloudApp
    networks:
      - my_network
    hostname: sberCloudApplication
    ports:
      - "8080:8080"
    restart: on-failure

  postgres:
    image: postgres:15-alpine
    container_name:   postgresnamecontainer
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: sberdatabase
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5442:5432" # если мы подключаемся внутри контейнера, то можно сразу стучаться на порт 5432 из pgadmin

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ad@min.ru
      PGADMIN_DEFAULT_PASSWORD: pgpassword
    volumes:
      - './pgadmin:/var/lib/pgadmin'
    ports:
      - 8081:80
volumes:
  postgres_storage:
    name: sberCloudApplicationVolume

networks:
  my_network:
    driver: bridge



